CREATE TABLE [dbo].[PMF_MASTER] (
    [CONTRACT]           NVARCHAR (20)   NOT NULL,
    [REF_CTR]            NVARCHAR (30)   NULL,
    [REF_CTR2]           NVARCHAR (30)   NULL,
    [DATE]               SMALLDATETIME   NULL,
    [SQ]                 NVARCHAR (6)    NULL,
    [ACCODE]             NVARCHAR (6)    NULL,
    [PT]                 NVARCHAR (30)   NULL,
    [PACKSIZE]           NVARCHAR (10)   NULL,
    [BRAND]              NVARCHAR (5)    NULL,
    [QTY]                FLOAT (53)      NULL,
    [UNIT]               NVARCHAR (6)    NULL,
    [DELI_QTY]           FLOAT (53)      NULL,
    [BAL_QTY]            FLOAT (53)      NULL,
    [PRICE]              FLOAT (53)      NULL,
    [TOTAL]              FLOAT (53)      NULL,
    [CURRENCY]           NVARCHAR (3)    NULL,
    [RATE]               FLOAT (53)      NULL,
    [PERIOD1]            SMALLDATETIME   NULL,
    [PERIOD2]            SMALLDATETIME   NULL,
    [BASIS]              NVARCHAR (10)   NULL,
    [BDES]               NVARCHAR (60)   NULL,
    [ACTIVE]             NVARCHAR (1)    NULL,
    [FCL]                NVARCHAR (4)    NULL,
    [CLOSE]              NVARCHAR (1)    NULL,
    [CLOSEDATE]          SMALLDATETIME   NULL,
    [CTR_TYPE]           NVARCHAR (1)    NULL,
    [BROKER]             NVARCHAR (5)    NULL,
    [BCOMM]              FLOAT (53)      NULL,
    [CURRENCY2]          NVARCHAR (3)    NULL,
    [SPEC]               NVARCHAR (30)   NULL,
    [SPEC1]              NVARCHAR (75)   NULL,
    [SPEC2]              NVARCHAR (75)   NULL,
    [SPEC3]              NVARCHAR (75)   NULL,
    [SPEC4]              NVARCHAR (75)   NULL,
    [SPEC5]              NVARCHAR (75)   NULL,
    [SPEC6]              NVARCHAR (75)   NULL,
    [SPEC7]              NVARCHAR (75)   NULL,
    [SPEC8]              NVARCHAR (75)   NULL,
    [SPEC9]              NVARCHAR (75)   NULL,
    [SPEC10]             NVARCHAR (75)   NULL,
    [SPEC11]             NVARCHAR (75)   NULL,
    [SPEC12]             NVARCHAR (75)   NULL,
    [DEST]               NVARCHAR (6)    NULL,
    [MILL]               NVARCHAR (6)    NULL,
    [AGENT]              NVARCHAR (5)    NULL,
    [SURVEYOR]           NVARCHAR (5)    NULL,
    [KPWX]               NVARCHAR (17)   NULL,
    [KQTY]               FLOAT (53)      NULL,
    [KDATE]              SMALLDATETIME   NULL,
    [PARTY_UTZ]          NVARCHAR (20)   NULL,
    [ETA]                SMALLDATETIME   NULL,
    [LYCAN1]             SMALLDATETIME   NULL,
    [LYCAN2]             SMALLDATETIME   NULL,
    [SI]                 NVARCHAR (1)    NULL,
    [PORT]               NVARCHAR (5)    NULL,
    [PAYMENT]            NVARCHAR (5)    NULL,
    [PAYMENT1]           NVARCHAR (60)   NULL,
    [PAYMENT2]           NVARCHAR (60)   NULL,
    [PAYMENT3]           NVARCHAR (60)   NULL,
    [PAYMENT4]           NVARCHAR (60)   NULL,
    [PAYMENT5]           NVARCHAR (60)   NULL,
    [TNS]                NVARCHAR (5)    NULL,
    [SI1]                NVARCHAR (75)   NULL,
    [SI2]                NVARCHAR (75)   NULL,
    [SI3]                NVARCHAR (75)   NULL,
    [SI4]                NVARCHAR (75)   NULL,
    [SI5]                NVARCHAR (75)   NULL,
    [SI6]                NVARCHAR (75)   NULL,
    [SI7]                NVARCHAR (75)   NULL,
    [SI8]                NVARCHAR (4000) NULL,
    [WQ]                 NVARCHAR (5)    NULL,
    [WQ1]                NVARCHAR (60)   NULL,
    [REM]                NVARCHAR (60)   NULL,
    [REM2]               NVARCHAR (60)   NULL,
    [REM3]               NVARCHAR (60)   NULL,
    [SIGNATURE]          NVARCHAR (60)   NULL,
    [STAFF]              NVARCHAR (5)    NULL,
    [STRINFO1]           NVARCHAR (60)   NULL,
    [STRINFO2]           NVARCHAR (60)   NULL,
    [STRINFO3]           NVARCHAR (60)   NULL,
    [STRINFO4]           NVARCHAR (60)   NULL,
    [STRINFO5]           NVARCHAR (60)   NULL,
    [ATTN]               NVARCHAR (40)   NULL,
    [CC1]                NVARCHAR (40)   NULL,
    [CC2]                NVARCHAR (40)   NULL,
    [CC3]                NVARCHAR (40)   NULL,
    [CC4]                NVARCHAR (40)   NULL,
    [CC5]                NVARCHAR (40)   NULL,
    [CC6]                NVARCHAR (40)   NULL,
    [COST]               DECIMAL (15, 2) NULL,
    [ENQUIRY]            NVARCHAR (6)    NULL,
    [EDATE]              SMALLDATETIME   NULL,
    [CREDIT_DAY]         INT             NULL,
    [PALMBASED]          VARCHAR (10)    NULL,
    [NEED_SURVEYOR]      BIT             NULL,
    [QTY_PER_CONTAINER]  FLOAT (53)      NULL,
    [PALLETIZED_PLASTIC] BIT             NULL,
    [PALLETIZED_WOODEN]  BIT             NULL,
    [PALLETIZED_PAPER]   BIT             NULL,
    [SHELF_LIFE]         INT             NULL,
    [COSTING]            VARCHAR (4000)  NULL,
    [REMARKS_OTHERS]     VARCHAR (300)   NULL,
    [CTRSERIAL]          VARCHAR (15)    NULL,
    [CNTTYPE]            NVARCHAR (1)    NULL,
    [FORMULA]            NVARCHAR (20)   NULL,
    [PRODUCT_ENQ]        NVARCHAR (10)   NULL,
    [VERIFYUSER]         CHAR (5)        NULL,
    [VERIFYTIME]         DATETIME        NULL,
    [APPUSER]            CHAR (5)        NULL,
    [APPTIME]            DATETIME        NULL,
    [SENTMAILCOUNT]      INT             NULL,
    [BULKOIL]            BIT             NULL,
    [PACK]               BIT             NULL,
    [PRINT_TESTMETHOD]   BIT             NULL,
    [DTRADE]             BIT             NULL,
    [EMAILSENT]          BIT             NULL,
    [EMAILSENT_DATE]     DATETIME        NULL,
    [INTERNAL_CTR]       BIT             NULL,
    [IS_CANCEL]          BIT             NULL,
    [CANCEL_REASON]      NVARCHAR (80)   NULL,
    [CONT_TYPE]          NVARCHAR (10)   NULL,
    [VERIFYUSER2]        CHAR (5)        NULL,
    [VERIFYTIME2]        DATETIME        NULL,
    [SPEC_EMAIL]         BIT             NULL,
    [CURRENCY3]          NVARCHAR (3)    NULL,
    [RATE3]              FLOAT (53)      NULL,
    [CARTON_FORMAT]      NVARCHAR (15)   NULL,
    [STICKER]            NVARCHAR (15)   NULL,
    [EMAILSENT_USER]     VARCHAR (5)     NULL,
    [SKIP_EMAIL]         BIT             NULL,
    [REVISION]           INT             NULL,
    [TEST]               NCHAR (10)      NULL,
    [REC_STATUS]         CHAR (1)        NULL,
    [NEWUSER]            CHAR (5)        NULL,
    [NEWTIME]            SMALLDATETIME   NULL,
    [MODIFYUSER]         CHAR (5)        NULL,
    [MODIFYTIME]         SMALLDATETIME   NULL,
    [Print Counter]      INT             NULL,
    [PRIMARY]            INT             NOT NULL,
    CONSTRAINT [PK_PMF_MASTER] PRIMARY KEY CLUSTERED ([CONTRACT] ASC) WITH (FILLFACTOR = 90)
);

