CREATE TABLE [dbo].[PMF_MASTER_SUB] (
    [ID]       INT            IDENTITY (1, 1) NOT NULL,
    [CONTRACT] NVARCHAR (20)  NOT NULL,
    [TEST] NCHAR(10) NULL, 
    [REMARKS]  NVARCHAR (200) NULL,
    CONSTRAINT [PK_PMF_MASTER_SUB] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PMF_MASTER_SUB_PMF_MASTER] FOREIGN KEY ([CONTRACT]) REFERENCES [dbo].[PMF_MASTER] ([CONTRACT])
);

